# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ML.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1367, 941)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1341, 921))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(430, 50, 541, 51))
        self.label.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(420, 320, 541, 141))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(1120, 670, 171, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(504, 39, 351, 71))
        self.label_2.setStyleSheet("\n"
"font: 81 20pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 270, 1331, 621))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(40, 10, 1271, 571))
        self.tableView.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableView_3 = QtWidgets.QTableView(self.tab_4)
        self.tableView_3.setGeometry(QtCore.QRect(170, 60, 931, 461))
        self.tableView_3.setObjectName("tableView_3")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(450, 20, 451, 561))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 10, 1191, 571))
        self.textEdit_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 160, 181, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 170, 181, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 160, 181, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(1080, 160, 181, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 30, 111, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(1190, 30, 111, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(430, 50, 561, 51))
        self.label_3.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 30, 111, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_10.setGeometry(QtCore.QRect(1190, 30, 111, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 200, 231, 51))
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_12.setGeometry(QtCore.QRect(300, 200, 231, 51))
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_13.setGeometry(QtCore.QRect(560, 200, 231, 51))
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_14.setGeometry(QtCore.QRect(820, 200, 231, 51))
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_15.setGeometry(QtCore.QRect(1080, 200, 231, 51))
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.tableView_2 = QtWidgets.QTableView(self.tab_7)
        self.tableView_2.setGeometry(QtCore.QRect(5, 291, 1321, 601))
        self.tableView_2.setObjectName("tableView_2")
        self.tabWidget.addTab(self.tab_7, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Maching Learning Project"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "NEXT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.label_2.setText(_translate("Form", "Deteails Dataset"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Tab 2"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">PassengerId      0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Survived         0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Pclass           0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Name             0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Sex              0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Age             86</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">SibSp            0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Parch            0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Ticket           0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Fare             1</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Cabin          327</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Embarked         0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:16pt; color:#000000; background-color:#ffffff;\">dtype: int64</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "Page"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\">&lt;class \'pandas.core.frame.DataFrame\'&gt;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\">RangeIndex: 418 entries, 0 to 417</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\">Data columns (total 12 columns):</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> #   Column       Non-Null Count  Dtype  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\">---  ------       --------------  -----  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 0   PassengerId  418 non-null    int64  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 1   Survived     418 non-null    int64  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 2   Pclass       418 non-null    int64  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 3   Name         418 non-null    object </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 4   Sex          418 non-null    object </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 5   Age          332 non-null    float64</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 6   SibSp        418 non-null    int64  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 7   Parch        418 non-null    int64  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 8   Ticket       418 non-null    object </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 9   Fare         417 non-null    float64</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 10  Cabin        91 non-null     object </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\"> 11  Embarked     418 non-null    object </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\">dtypes: float64(2), int64(5), object(5)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.77%; background-color:#ffffff;\"><span style=\" font-family:\'menlo,consolas,DejaVu Sans Mono,monospace\'; font-size:11pt; font-style:italic; color:rgba(0,0,0,0.866667); background-color:#ffffff;\">memory usage: 39.3+ KB</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Page"))
        self.pushButton_3.setText(_translate("Form", "view data"))
        self.pushButton_4.setText(_translate("Form", "describe data"))
        self.pushButton_5.setText(_translate("Form", "NUll"))
        self.pushButton_6.setText(_translate("Form", "infotmatiom"))
        self.pushButton_7.setText(_translate("Form", "Back"))
        self.pushButton_8.setText(_translate("Form", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.label_3.setText(_translate("Form", "Cleaning and Preprocessing"))
        self.pushButton_9.setText(_translate("Form", "Back"))
        self.pushButton_10.setText(_translate("Form", "Next"))
        self.pushButton_11.setText(_translate("Form", "drop_unnecessary_columns"))
        self.pushButton_12.setText(_translate("Form", "handle_missing_values"))
        self.pushButton_13.setText(_translate("Form", "encode_categorical_features"))
        self.pushButton_14.setText(_translate("Form", "engineer_features"))
        self.pushButton_15.setText(_translate("Form", "scale_numerical_features"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "Page"))
